### ISSUE TITLE
OSX build not up-to-date?

### ISSUE THREAD

**Issue by spennihana** [conda-forge/r-pbdzmq-feedstock#3]
https://anaconda.org/conda-forge/r-pbdzmq

still lists 0.2_4 instead of 0.3_1

**Comment by jdblischak** [comment]
@spennihana The macOS builds took a lot longer to build (probably due to a Travis CI backlog), but it appears they are available now.

https://anaconda.org/conda-forge/r-pbdzmq/files?version=0.3_1

Could you please confirm and then close this Issue?

**Comment by dbast** [comment]
Seems to be resolved.
